---
- name: Set subdomain to use
  set_fact:
    nodejs_url_subdomain: "{{ nodejs_package_ext[ansible_distribution] }}"

  # https://github.com/nodesource/distributions/blob/master/README.md
- name: Download installation script
  get_url:
    url: "https://{{ nodejs_url_subdomain }}.nodesource.com/setup_{{ nodejs_version }}.x"
    dest: "{{ nodejs_setup_tmp }}"
  register: response
  changed_when: "response.status_code != 200"

- name: Run installation script
  command: "bash {{ nodejs_setup_tmp }}"
  register: result
  changed_when: "'To install' not in result.stdout"

- name: Clean
  file:
    path: "{{ nodejs_setup_tmp }}"
    state: absent
  register: result
  changed_when: "result.diff.before.state != 'file' or result.diff.after.state != 'absent'"

- name: Ubuntu support
  when: ansible_distribution == 'Ubuntu'
  block:

    - name: Install dependencies
      apt:
        name:
          - gcc
          - g++
          - make
        state: present

    - name: Install
      apt:
        name: nodejs
        state: latest
        update_cache: yes

- name: CentOS support
  when: ansible_distribution == 'CentOS'
  block:

    - name: Install dependencies
      yum:
        name:
          - gcc-c++
          - make
        state: present

    - name: Install
      yum:
        name: nodejs
        state: latest
        update_cache: yes

- name: Make sure that nodejs alias exists
  file:
    src: /usr/bin/node
    dest: /usr/bin/nodejs
    state: link

- name: Make sure that newest npm version have been installed
  npm:
    name: npm
    global: yes

- name: Configure npm
  template:
    src: "npmrc.j2"
    dest: "{{ '/' if item.user == 'root' else '/home' }}/{{ item.user }}/.npmrc"
    mode: 0600
    owner: "{{ item.user }}"
  loop: "{{ nodejs_npm_config }}"
  when: nodejs_npm_config | length > 0

- name: Installing requested global npm packages
  npm:
    name: "{{ item }}"
    global: yes
    state: present
  loop: "{{ nodejs_npm_install_globally }}"
  when: nodejs_npm_install_globally | length > 0
